const fortunes=[
 {name:'海の支配者',face:1,lines:['今日はお前がルールだ。まあ、水槽の中だけだけどな。','調子に乗れ。珍しく、お前に追い風が吹いてる。','エサに困らない日。人間関係は知らん。','偉そうにしていい日。たぶん誰も止めない。','今日は勝てる。しれっと勝て。']},
 {name:'背びれ絶好調',face:2,lines:['背びれが立ってる。お前のやる気も、それくらい見せろ。','今日は少しだけイケてる。勘違いは明日からにしろ。','なんか勢いがある日。壁にぶつかる前に泳げ。','小さな勝ちを拾える。落とすなよ。','まあまあ調子いい。欲張ると浅瀬に乗り上げるぞ。']},
 {name:'エサ発見',face:3,lines:['欲しいものが見つかる。取り逃がすな、遅そうだから。','目の前にチャンス。口を開けて待つだけはやめろ。','今日は腹が減ってるくらいがちょうどいい。','小さなご褒美がある。大騒ぎするほどではない。','食いつきどころを間違えるな。何でも噛むな。']},
 {name:'水槽の主',face:4,lines:['悪くない日。お前も一応、主役っぽく見える。','いつもの場所で輝け。外海に出る勇気はまだ要らん。','平和な一日。余計なことをしなければな。','居場所があるって、地味にすごい。感謝しとけ。','今日は水槽の中心。照明は当たってないけど。']},
 {name:'小魚メンタル',face:5,lines:['気にしすぎ。誰もお前のことそんなに見てない。','その一言、たぶん深い意味ない。深海まで潜るな。','自信はない。けど予定は進む。泳げ。','弱気でも行ける。小魚なりの機動力を見せろ。','今日は静かにしてろ。無駄にヒレを広げるな。']},
 {name:'浅瀬で迷子',face:6,lines:['方向感覚がない日。地図を見るという進化をしろ。','あれこれ始めるな。一個だけ終わらせろ。','迷ってるうちに日が暮れるぞ。まあ、いつものことか。','今日は寄り道が多い。目的地は遠い。','助けを呼べ。サメでも迷子になる。お前だけじゃない。']},
 {name:'干からび寸前',face:7,lines:['今日は無理するな。干物になる前に休め。','運勢は低空飛行。お前のせいではなく、たぶん潮のせい。','やる気が砂浜に置いてきぼり。回収は明日でいい。','頑張るより、寝ろ。反論は受け付けない。','今日は生存で合格。以上。']}
];
const card=document.querySelector('#card'),slot=document.querySelector('#slot'),reel=document.querySelector('#reel'),shark=document.querySelector('#shark'),nameEl=document.querySelector('#fortune-name'),message=document.querySelector('#message'),button=document.querySelector('#spin'),blast=document.querySelector('#blast');
let current=0,spinning=false,taps=[],spinTimer;
function tile(f){return '<div class="shark-tile"><img class="shark-face" src="naoking-'+f.face+'.png" alt="なおキング"></div>'}
button.addEventListener('click',()=>{if(blast.hidden===false)return;const now=Date.now();taps=taps.filter(t=>now-t<2400);taps.push(now);if(taps.length>=5){clearTimeout(spinTimer);spinning=false;slot.classList.remove('is-spinning');blast.hidden=false;card.classList.add('is-exploded');nameEl.textContent='なおキング激怒';message.textContent='連打されたので、今日の運勢はもう壊れた。';button.textContent='なおキング、停止中…';setTimeout(()=>{blast.hidden=true;card.classList.remove('is-exploded');taps=[];button.textContent='運命を回す'},2600);return}if(spinning)return;spinning=true;button.textContent='なおキング、裁定中…';message.textContent='なおキングが今日の運勢を読んでいる……たぶん適当だ。';reel.innerHTML=fortunes.concat(fortunes,fortunes).map(tile).join('');slot.classList.add('is-spinning');const next=Math.floor(Math.random()*fortunes.length);spinTimer=setTimeout(()=>{const f=fortunes[next];current=next;slot.classList.remove('is-spinning');reel.innerHTML=tile(f);nameEl.textContent=f.name;message.textContent=f.lines[Math.floor(Math.random()*f.lines.length)];button.textContent='運命を回す';spinning=false},1700)});
